### PR TITLE
Create Arpit Jain

### PR DESCRIPTION
**Pull request by arpitjainds**

### CODE REVIEW

**Comment by arpitjainds** [comment]
I just joined the Organization. So exciting 👍

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Looks awesome @arpitjainds 
However you might want to add you details to the `include.js` file, so your work shows up on the index page.
If you want to go ahead and make those changes we can merge this in 😄

**Comment by arpitjainds** [comment]
Just made all the Changes!

**Comment by SamirJouni** [comment]
Good Job!

**Pull request merged**
