### PR TITLE
Virag

### PR DESCRIPTION
**Pull request by virag-ky**
I tried to re-create my chihuahua and added animation to the ears.

### CODE REVIEW

**Review by donmarvex — COMMENTED** [review]
Hello @virag-ky , thank You for the changes made. They look amazing. I noticed you changed a few single quotes to double quotes and also the tab spacing from lines 27 to 33.
Would it be nice to automate this process with GitHub actions using prettier to automatically format code.

You can have a look at the implementation by @sophiabrandt in https://github.com/zero-to-mastery/Animation-Nation/pull/915 .

Other than that, everything looks perfect!

**Comment by virag-ky** [comment]
Thank you for the feedback, however, I looked at the implementation of the prettier formatter and there are no clear instructions on how to implement it.  I also did not change any quotes, maybe you can show me the file in which the quotes changed... My VSCode is using its prettier extension, perhaps that's the case...

**Comment by donmarvex** [comment]
> Thank you for the feedback, however, I looked at the implementation of the prettier formatter and there are no clear instructions on how to implement it.  I also did not change any quotes, maybe you can show me the file in which the quotes changed... My VSCode is using its prettier extension, perhaps that's the case...

Yes, it was definitely your prettier extension on VS code that made those changes. You can check them out in the files changed tab or take a look at the summary of commits.

See a snippet of the changes below 

As for the implementation, @sophiabrandt can effect those changes.

**Comment by sophiabrandt** [comment]
Yes, it is a bit unfortunate that additional cosmetic changes were made. Oftentimes, code extensions like prettier will auto-format on save and use different settings.

But it doesn't break anything, and this is not production code. 🤷 

I will add a Github action for formatting.

**Comment by virag-ky** [comment]
Okay, I understand, thank you so much.

**Pull request merged**
