### PR TITLE
Added Chai in art

### PR DESCRIPTION
**Pull request by patelvivekdev**
added Cup of Chai_lover..

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
Please only change your files. You have also changed files in the `Art/Heart` folder, why is that?

**Comment by patelvivekdev** [comment]
> Please only change your files. You have also changed files in the `Art/Heart` folder, why is that?

I didn't change that when i fork that with github desktop it already show in that

**Comment by patelvivekdev** [comment]
What should I do now?

**Comment by sophiabrandt** [comment]
@Vivek2509 can you sync your fork to upstream and then push again?
https://www.freecodecamp.org/news/how-to-sync-your-fork-with-the-original-git-repository/
After you've done that, and it still doesn't work, I can try to manually fix it when I have time. Thank you.

**Pull request closed without merging**
