### PR TITLE
Adding new art Pikachu-face

### PR DESCRIPTION
**Pull request by JJang95**
Added submission

### CODE REVIEW

**Review by JJang95 — COMMENTED** [review]
Added angry_bird img

**Review by JJang95 — COMMENTED** [review]
Finished Angrybird/pikachu face

**Comment by JJang95** [comment]
Made Ramen_bowl contribution

**Review by JJang95 — COMMENTED** [review]
Made contributions

**Review by JJang95 — COMMENTED** [review]
Added Ramen_bowl image

**Review by JJang95 — COMMENTED** [review]
Added Ramen_bowl includes/removed extra img file

**Review by WitchDevelops — COMMENTED** [review]
Code looks good, art looks good, but it's note responsive due to using px units.

**Pull request closed without merging**
